app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace="main")),
    path('catalog/', include("goods.urls", namespace="catalog")),
    path('users/', include("users.urls", namespace="user")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
import main.views

app_name = "main"
urlpatterns = [
    path('', main.views.index, name='main_page'),
    path('about/', main.views.about, name='about_us'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_project/urls.py
from django.contrib import admin
from django.urls import path

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('order', views.create_order, name='create_order'),
]

cart/models.py
from django.db import models

from goods.models import Products
from users.models import User


class CartQuerySet(models.QuerySet):
    def total_price(self):
        return sum(cart.product_cost() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=40, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = 'Корзину'
        verbose_name_plural = 'Корзины'

    objects = CartQuerySet().as_manager()

    def product_cost(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f"Пользователь - {self.user} | Товар - {self.product.name} | Количество - {self.quantity}"  # мы можем использовать на методы классов на которые ссылаемся в ForeignKey

cart/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string

from cart.models import Cart
from cart.utils import get_user_carts
from goods.models import Products


def cart_add(request):
    product_id = request.POST.get('product_id')
    product = Products.objects.get(id=product_id)  # создаём объект product и получаем по слагу сам продукт, а не просто переданную строку product_slug
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user,product=product)  # затем создаём карту где фильтруем по имени пользователя и товару
        # мы можем обращаться к user из-за того что у нас в таблице есть колонка user которая ссылается на него в таблице
        if carts.exists():
            cart = carts[0]  # берём первый товар в карте потому что только одно название товара может содержаться в одной карте клиента
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product,quantity=1)  # если карты нет, то сохраняем карту с одним объектом продукта
    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, product=product)
        if carts.exists():
            cart = carts[0]
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, product=product,quantity=1)
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        'cart/cart_items.html',{'carts':user_cart}, request=request)
    response_data = {
        'success': 'Товар добавлен в корзину',
        'cart_items_html': cart_items_html,
    }

    return JsonResponse(response_data)


def cart_change(request):
    cart_id = request.POST.get('cart_id', None)
    quantity = request.POST.get('quantity', None)
    cart = Cart.objects.get(id=cart_id)
    cart.quantity = quantity
    cart.save()
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        'cart/cart_items.html', {'carts': user_cart}, request=request)

    response_data = {
        'message': 'Товар добавлен в корзину',
        'cart_items_html': cart_items_html,
        'quantity': cart.quantity,
    }
    return JsonResponse(response_data)


def cart_remove(request):
    print("POST:", request.POST)
    cart_id = request.POST.get('cart_id')
    cart = Cart.objects.get(id=cart_id)
    cart.delete()
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        'cart/cart_items.html', {'carts': user_cart}, request=request)
    response_data = {
        'message': 'Товар удалён из корзины',
        'cart_items_html': cart_items_html,
    }
    return JsonResponse(response_data)

cart/templates/cart/cart_items.html
{% load cart_tags %}
{% load static %}
{% cart_count request as cart %}
{% if cart %}
    <h3>Ваша корзина</h3>
{% else %}
    <h3>Пусто, если что-то хочешь увидеть, добавь товар</h3>
{% endif %}
{% for cart in cart %}

    <div class="cart-item" id= {{ item.id }}>
        <div class="item-name">{{ cart.product.name }}</div>
        <div class="input-group"> {# без этого не передаётся в js input#}
            <div class="custom-number-input">
                    <span class="input-group-btn">
                    <button type="button" class="decrement" data-cart-id="{{ cart.id }}"
                            data-cart-change-url="{% url 'cart:cart_change' %}">
                        {% csrf_token %}
                        −</button>
                        </span>
                <input type="text" class="number" value="{{ cart.quantity }}" readonly>
                <span class="input-group-btn">
                    <button type="button" class="increment" data-cart-id="{{ cart.id }}"
                            data-cart-change-url="{% url 'cart:cart_change' %}">
                        {% csrf_token %}
                        +</button>
                    </span>
            </div>
        </div>
        <div class="item-price" data-unit-price="{{ cart.product.price }}">
            {{ cart.product_cost }}$
        </div>
        <div class="">
            {# возможно но не факт если это вынести в отдельный файл и поставить сюда <div id="cart-items-container"> #}
            <a class="remove-button remove-from-cart" href="{% url 'cart:cart_remove' %}"
               data-cart-id="{{ cart.id }}">Удалить</a>
        </div>
    </div>
{% endfor %}
{% if cart %}
    <a type="submit" href="{% url 'orders:create_order' %}" class="update-btn">Перейти к
        оформлению {{ cart.total_price }}$</a>
{% endif %}

cart/templates/cart/no_name_client.html
{% extends "base.html" %}
{% load static %}
{% load cart_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
{% endblock %}
{% block about %}
    <div class="left">
        <a href="{% url 'main:main_page' %}" class="filter-btn">Назад</a>
    </div>
    <body>
    <div class="profile-container">
        <!-- Карзина -->
        <div id="cart-items-container"> {# эта строка есть в js и без неё не передаётся эта страница  #}
            {% include "cart/cart_items.html" %}
        </div>
    </div>
    </body>
    <img src="{% static 'main/image/city.png' %}" alt="" class="background-image">
{% endblock %}