app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace="main")),
    path('catalog/', include("goods.urls", namespace="catalog")),
    path('users/', include("users.urls", namespace="user")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('order', views.create_order, name='create_order'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('user_cart/', views.user_cart, name='user_cart'),
]

orders/models.py
from django.db import models

from goods.models import Products
from users.models import User

#Это расширение стандартного QuerySet. То есть я создаю свой класс,
# который добавляет дополнительные методы к обычным запросам через ORM.
# и теперь я смогу вызвать вот так это OrderItem.objects.total_price()
#OrderItem.objects.total_quantity()
class OrderitemQuerySet(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name='Пользователь',default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = "Заказы"

    def __str__(self):
        username = self.user.username if self.user else "аноним"
        return f"Заказ № {self.pk} | Покупатель {username}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name='Продукт',default=None)
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.IntegerField(default=1, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товары'

    objects = OrderitemQuerySet.as_manager()

    def products_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f'Товар {self.name} | Заказ № {self.order.pk}'

orders/forms.py
import re

from django import forms


class CreateOrderForm(forms.Form):
    username = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(choices=[("0", False),("1", True),],)
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=[("0", False),("1", True),],)

    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]
        pattern = re.compile(r'^\+\d{6,14}$')
        if not pattern.match(data):
            raise forms.ValidationError("Номер телефона должен начинаться с + и содержать только цифры, минимум 6.")
        return data

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db import transaction
from django.shortcuts import render, redirect

from cart.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from orders.tasks import add_to_queue


@login_required
def create_order(request):
    if request.method == "POST":  # Если POST — значит он отправил форму. Если GET — значит просто зашёл на страницу
        form = CreateOrderForm(data=request.POST)  # создаём новую форму
        if form.is_valid():  # в основном не проходит потому что не все параметры получены, если надо узнать

            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)
                    products_all = []
                    order = Order.objects.create(  # создаём заказ именно 1 заказ и привязываем их к пользователю
                        user=user,
                        delivery_address=form.cleaned_data['delivery_address'],
                        phone_number=form.cleaned_data['phone_number'],
                        requires_delivery=form.cleaned_data['requires_delivery'],
                        payment_on_get=form.cleaned_data['payment_on_get'],
                        status='Товар оформляется и что-то может пойти не так',
                    )

                    for cart_item in cart_items:  # проходимся циклом по корзине текущего пользователя
                        product = cart_item.product  # это объект, мы ссылаемся по foreign key
                        name = cart_item.product.name  # берём название продукта
                        price = cart_item.product.price  # берём цену продукта
                        quantity = cart_item.quantity  # так же количество

                        if product.quantity < quantity:  # проверяем не больше ли заказали чем у нас на сладе
                            raise ValidationError(f'Недостаточное количество товара {name} на складе\
                                             В наличии  {product.quantity}')  # если на складе меньше чем заказали поднимаем сообщение

                        OrderItem.objects.create(  # это создание записи в бд, одного товара
                            order=order,  # это ссылка на order
                            product=product,  # конкретный продукт
                            name=name,  # это название продукта
                            price=price,  # его название
                            quantity=quantity,  # и количество

                        )
                        products_all.append((product.id,quantity))
                        product.save()

                    cart_items.delete()
                    add_to_queue.delay_on_commit(
                        order_id=order.id,
                        prod=products_all
                    )
            except ValidationError as e:
                messages.success(request, str(e.messages[0]))
                return redirect('user:profile')


            messages.success(request, 'Заказ будет ждать оформления')
            return redirect('user:profile')
    else:
        initial = {
            'username': request.user.username,  # если вызываем метод get, то подставляем в поля значения
            'phone_number': request.user.number,
        }
        form = CreateOrderForm(initial=initial)  # если get запрос создаём форму передавая initial
    context = {
        'title': "Оформление заказа",
        'form': form,
    }
    return render(request, 'orders/order.html', context)

orders/templates/orders/order.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tags %}
{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/orders.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
{% endblock %}

{% block about %}
    <div class="left">
        <a href="{% url 'user:profile' %}" class="filter-btn">Назад</a>
    </div>
    <div class="order-wrapper">
        <h2>Оформление заказа</h2>
        <form method="POST" action="{% url 'orders:create_order' %}">
            {% csrf_token %}
            {% cart_count request as cart_items %}
            {% for cart in cart_items %}
                <div class="cart-item">
                    <div class="item-details">
                        <p><strong>Наименование:</strong> {{ cart.product.name }}</p>
                        <p><strong>Количество:</strong> {{ cart.quantity }}</p>
                        <p><strong>Цена:</strong> {{ cart.product_cost }}</p>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <label for="id_username">Имя</label>
                <input type="text" id="id_username" name="username" class="form-control"
                       value='{% if form.username.value %}{{ form.username.value }}{% endif %}' required>
            {#form передаём в контексте во views чтобы тут юзать#}
            {# (data=request.POST) оно создаёт форму которая собирает с input, инфу name и чему оно равно#}
            {# то есть оно передаёт в name то что в value и теперь username = value#}
            </div>
            {% if form.username.errors %}
                <div class="form-text">{{ form.username.errors }}</div>
            {% endif %}

            <div class="form-group">
                <label for="id_phone_number">Телефон</label>
                <input type="text" id="id_phone_number" name="phone_number"
                       value='{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}'
                        placeholder="+375231234587" required>
                {#  если у тебя в form написано phone_number то и тут так какие там поля есть такие все должны быть тут#}
            </div>
            {% if form.phone_number.errors %}
                <div class="form-text">{{ form.phone_number.errors }}</div>
            {% endif %}

            <div class="form-group">
                <label for="id_payment_on_get">Способ оплаты</label>
                <div class="form-check">
                    <input id="id_payment_on_get" name="payment_on_get" type="radio" value="0" checked>
                    <label for="id_payment_on_get">Оплата картой</label>
                </div>
                <div class="form-check">
                    <input id="id_payment_on_get" name="payment_on_get" type="radio" value="1" checked>
                    <label for="id_payment_on_get">Наличными/картой при получении</label>
                </div>
            </div>
            {% if form.phone.errors %}
                <div class="form-text">{{ form.phone.errors }}</div>
            {% endif %}

            <div class="form-group">
                <label for="id_requires_delivery">Способ доставки</label>
                <div class="form-check">
                    <input id="id_requires_delivery" name="requires_delivery" type="radio" value="1" checked>
                    <label for="id_requires_delivery">Нужна доставка</label>
                </div>
                <div class="form-check">
                    <input id="id_requires_delivery" name="requires_delivery" type="radio" value="0" checked>
                    <label for="id_requires_delivery">Самовывоз</label>
                </div>

                {% if form.requires_delivery.errors %}
                    <div class="form-text">{{ form.requires_delivery.errors }}</div>
                {% endif %}
            </div>
            <div id="delivery_fields" class="form-group hidden">
                <label for="id_delivery_address">Адрес доставки</label>
                <input type="text" id="id_delivery_address" name="delivery_address"
                       value="{{ form.delivery_address.value|default_if_none:'' }}"
                       placeholder="Город, улица, дом, квартира">

            </div>
            {% if form.delivery_address.errors %}
                <div class="form-text">{{ form.delivery_address.errors }}</div>
            {% endif %}

            <button type="submit" class="checkout-btn">Оформить весь заказ</button>
        </form>

    </div>
    <script src="{% static 'main/js/orders.js' %}"></script>
    <img src="{% static 'main/image/city.png' %}" alt="" class="background-image">
{% endblock %}