app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace="main")),
    path('catalog/', include("goods.urls", namespace="catalog")),
    path('users/', include("users.urls", namespace="user")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = "goods"



urlpatterns = [
    path('search/', views.catalog, name='search'),
    # category_slug>/' это передаётся в функцию на которую ссылается этот путь иначе не поймёт
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
import main.views

app_name = "main"
urlpatterns = [
    path('', main.views.index, name='main_page'),
    path('about/', main.views.about, name='about_us'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_project/urls.py
from django.contrib import admin
from django.urls import path

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

goods/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=150, unique=True, null=True, blank=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=150, unique=True, null=True, blank=True, verbose_name='URL')
    description = models.TextField(verbose_name="Описание")
    price = models.IntegerField(default=1, verbose_name='Цена')
    image = models.ImageField(upload_to='goods_images', verbose_name='Изображение')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name="Категория")

    class Meta:
        db_table = 'product'
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'product_slug': self.slug})

    def display_id(self):
        return f'{self.id:05}'

# ./manage.py dumpdata goods.Products > fixtures/good/products.json это чтобы сделать фикстуры

goods/views.py
from django.core.cache import cache
from django.core.paginator import Paginator
from django.shortcuts import render

from goods.models import Products
from goods.utils import search


def get_products_from_cache(s_by_category=None,c_slug=None):
    if not s_by_category:
        cache_key = f'products_{c_slug}'
    else:
        cache_key = f'products_{s_by_category}'
    cached_products = cache.get(cache_key)   # получаем из кэша нужные данные по ключу
    if cached_products is None:  # если данных нет, то вручную берём нужный объект
        if c_slug == 'all':
            products = Products.objects.all().order_by('id') # это можно сказать sql запрос SELECT * FROM Products и он помещает в переменную всё, что ты выбрал
        elif s_by_category:
            products = Products.objects.filter(category__slug=s_by_category).order_by('id')
        else:
            products = Products.objects.filter(category__slug=c_slug).order_by('id')   # category__slug это делается
        cache.set(key=cache_key, value=products, timeout=60)  # и кешируем его по ключу, данным и времени жизни кэша
    # когда есть связь между таблицами, category это название столбца в Products, а slug - это поле модели Categories,
    # которое мы хотим использовать для фильтрации. Эта вся строка буквально означает мы выведем все продукты у которых
    #в категории находится та категория, которую мы прокинули, а __ - это синтаксис Django ORM для обращения к связным таблицам
    else:
        products = cached_products   # возвращаем products в любом случае поэтому переопределяем cached_products

    return products

def catalog(request, category_slug=None):
    search_by_category = request.GET.get('category')
    query = request.GET.get('q')
    page = request.GET.get('page', 1)
    if query:
        products = search(query, search_by_category).order_by('id')
    else:
        products = get_products_from_cache(s_by_category=search_by_category,c_slug=category_slug)
    paginator = Paginator(products, 4)
    current_page = paginator.page(int(page))
    context = {
        'request_slug': search_by_category,
        'title': 'Goods',
        'products': current_page,
        'page': page,
        'slug': category_slug,
    }
    return render(request, 'goods/catalog.html', context)



def product(request, product_slug):
    products = Products.objects.get(slug=product_slug)
    context = {
        'title': 'Description',
        'product': products,
    }
    return render(request, 'goods/product.html', context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}
{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/catalog.css' %}">
{% endblock %}
{% block about %}
    <body>
    <header>
        <h1 class="lo">Каталог товаров</h1>
    </header>
    <div class="left">
        <a href="{% url 'main:main_page' %}" class="filter-btn">Назад</a>
    </div>

    <!-- Выпадающий фильтр по категориям -->
    <div class="category-filter">
        <label for="categorySelect"></label>
        <select id="categorySelect" class="category-dropdown"
                onchange="window.location.href = '/catalog/' + this.value + '/'">
            {% tag_categories as categories %}
            {% for category in categories %}
                <option value="{{ category.slug }}"
                        {% if request_slug %}{% if category.slug == request_slug %}selected{% endif %}>
                            {% else %}{% if category.slug == slug %}selected{% endif %}>{% endif %}
                        {{ category.name }}
                </option>
            {% endfor %}
        </select>
    </div>
    <!-- Форма поиска -->
    <form role="search" method="GET" action="{% url 'catalog:search' %}?category={{ slug }}" class="search-container">
        <label>
            <input type="search" name="q" class="search-box" placeholder="Поиск по товарам...">
            <input type="hidden" name="category"
                   value="{% if request.GET.category %}{{ request_slug }}{% else %}{{ slug }}{% endif %}">
            {# сверху request_slug это как request.GET.category потому что это прокидывается во views как search_by_category = request.GET.get('category', None) #}
            <button type="submit" class="search-btn">🔍</button>
        </label>
    </form>
    <main class="catalog">
        {% for product in products %}
            <div class="product-card description" data-category="{{ product.category.id }}">
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                <h2>{{ product.name }}</h2>
                <h2>id - {{ product.display_id }}</h2>
                <p class="price">{{ product.price }} $</p>
                <a class="filter-btn" href="
                        {% url 'goods:product' product.slug %}{% if request.GET.category %}?q={{ request.GET.q }}&category={{ request_slug }}{% else %}?category={{ slug }}{% endif %}&page={{ page }}">Подробнее</a>
            </div>
        {% endfor %}
    </main>
    <img src="{% static 'main/image/back.png' %}" alt="" class="background-image">
    <script src="{% static 'main/js/catalog.js' %}"></script>
    {% if products %}
        <div class="pagination">
            <a class="page-btn {% if not products.has_previous %}disabled{% endif %}" href="?{% change_param page=1 %}">Первая</a>
            {% if products.has_previous %}
                <a class="page-btn" href="?{% change_param page=products.previous_page_number %}">‹</a>
            {% else %}<span class="page-btn disabled">‹</span>
            {% endif %}
            <span class="current-page">Страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
            {% if products.has_next %}
                <a href="?{% change_param page=products.next_page_number %}" class="page-btn">›</a>
            {% else %}<span class="page-btn disabled">›</span>
            {% endif %}
            <a href="?{% change_param page=products.paginator.num_pages %}"
               class="page-btn {% if not products.has_next %}disabled{% endif %}">Последняя</a>
        </div>
    {% else %}
        <div class="nothing-find">
            <p>Ничего не найдено...</p>
        </div>
    {% endif %}
    </body>
{% endblock %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load goods_tags %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/product.css' %}">
{% endblock %}

{% block about %}
    <body>
    <img src="{% static 'main/image/back.png' %}" alt="{{ product.name }}" class="background-image">
    <!-- Фон выше контента -->
    <main class="product-detail" >
        <div class="product-info">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
            <div class="product-details description">
                <h2>{{ product.name }}</h2>
                <p class="product-id">ID: {{ product.display_id }}</p>
                <p class="product-price">Цена: {{ product.price }} $</p>
                <p class="product-description">{{ product.description }}</p>
            </div>
        </div>
    </main>

    <a href="{% url 'cart:cart_add' %}" class="filter-btn fp add-to-cart" data-product-id="{{ product.id }}">{% csrf_token %}Добавить в корзину</a>

    <div class="left">
        <a href="
                {% if request.GET.q %}{% url 'goods:search' %}?{% change_param %}{% elif request.GET.category %}{% url 'goods:index' request.GET.category %}?{% change_param %}{% endif %}"
                {#если делается запрос тогда передаётся параметр q то оно переопределяет начальный путь который был взят из change_param(url который сейчас на странице)#}
                {#и дальше передаёт запросом весь change_param а именно page, q и category и получается что нас перекидывает на страницу goods:search и подставляет эти#}
                {#параметры| 2 часть в другом случае также переопределяется как и в 1 части но ещё надо прокинуть category_slug, делается это запросом #}

           {% if request.GET %}class="filter-btn">Назад</a>{% else %}{% endif %}
    </div>
    </body>
{% endblock %}