app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace="main")),
    path('catalog/', include("goods.urls", namespace="catalog")),
    path('users/', include("users.urls", namespace="user")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
import main.views

app_name = "main"
urlpatterns = [
    path('', main.views.index, name='main_page'),
    path('about/', main.views.about, name='about_us'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_project/urls.py
from django.contrib import admin
from django.urls import path

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('user_cart/', views.user_cart, name='user_cart'),
]

main/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title': 'BioHack Systems',
        'button_1': 'order',
        'button_2': 'Информация о нас',
    }
    return render(request, 'main/index.html', context)


def about(request):
    context = {
        'title': 'О нас',
        'about_us': 'О нас – BioHack Systems',
        'text': [
            'Добро пожаловать в BioHack Systems — лидера в сфере кибернетических улучшений и интеграции человека с технологиями.',
            'Мы создаем импланты и нейроинтерфейсы нового поколения, расширяя границы человеческих возможностей c 2043 года.',
            'Наши разработки обеспечивают точность, силу, скорость и безопасность, необходимые в современном мире.',
            'Мы работаем без компромиссов, предоставляя каждому клиенту не просто продукт, а индивидуальное решение, соответствующее его потребностям.',
            'Каждая установка, каждая модификация — это шаг в будущее, где технологии работают на вас.',
            'Наши технологии разрабатываются лучшими специалистами в области биоинженерии, нейротехнологий и кибернетики.',
            'Мы используем только передовые материалы и алгоритмы адаптивного контроля, чтобы обеспечить бесшовную интеграцию имплантов с нервной системой.',
            'Каждое улучшение проходит строгие испытания, гарантируя стабильность, долговечность и полную совместимость с телом пользователя.',
            'Мы ценим доверие наших клиентов и гарантируем, что каждый, кто выберет BioHack Systems, получит качество, надежность и поддержку на всех этапах.',
            'Мы предлагаем индивидуальные настройки, позволяя каждому клиенту раскрыть свой потенциал без ограничений.',
            'BioHack Systems — это не просто корпорация, это новый этап эволюции.',
            'В основе BioHack Systems лежит один принцип — совершенство во всем.',
            'Будущее начинается здесь.'
        ]}
    return render(request, 'main/about_us.html', context)

main/templates/main/about_us.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'main/css/about_us.css' %}">
{% endblock %}
{% block about %}
<body>
<div class="animated-stripes">
    <div class="stripe"></div>
    <div class="stripe"></div>
    <div class="stripe"></div>
    <div class="stripe"></div>
    <div class="stripe"></div>
</div>
<div class="left">
    <a href="{% url 'main:main_page' %}" class="btn">Назад</a>
</div>
<div class="about-container description">
    <h1 id="about-text ">{{ about_us }}</h1>
    <div id="text-container">
        {% for para in text %}
        <p class="fade-text">{{ para }}</p>
        {% endfor %}
    </div>
</div>
<script src="{% static 'main/js/script.js' %}"></script>
</body>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load goods_tags %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/main_page.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
{% endblock %}
{% block about %}
    <body>
    {% if not user.is_authenticated %}
        <a href="{% url 'user:login' %}" class="image">
            <img src="{% static 'main/image/basket.png' %}" class="image" alt="Корзина">
        </a>
        <div class="top-right">
            <a href="{% url 'user:registration' %}" class="btn">Регистрация</a>
            <a href="{% url 'user:user_cart' %}" class="btn">Pro</a>
        </div>
    {% endif %}
    <div class="left-column">

        <a href="{% url 'catalog:index' category_slug='all' %}" class="btn">{{ button_1 }}</a>
        {% if user.is_superuser or user.is_staff %}
            <a href="{% url 'admin:index' %}" class="btn">Админ</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'user:logout' %}" class="btn">Выйти</a>
            <a href="{% url 'user:profile' %}" class="btn">Профиль</a>

        {% endif %}
    </div>
    </body>
{% endblock %}
{% block footer %}
    <footer>
        <p>Copyright © 2043-2088 NeuroForge. Все права защищены.</p>
        <a href="{% url 'main:about_us' %}">{{ button_2 }}</a>
        <p>Связаться с нами: support@neuroforge.com</p>
    </footer>
    <img src="{% static 'main/image/city.png' %}" alt="" class="background-image">
{% endblock %}